version: "3.9"
services:
  app:
    image: community-bookshelf:latest
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - "3000:80"
    volumes:
      - /var/community-bookshelf/storage:/rails/storage
